# Generated by Django 5.1.5 on 2025-01-23 10:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aplikacja', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Stanowisko',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nazwa', models.CharField(max_length=60)),
                ('opis', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Osoba',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imie', models.CharField(max_length=60)),
                ('nazwisko', models.CharField(max_length=60)),
                ('plec', models.IntegerField(choices=[(1, 'Kobieta'), (2, 'Mężczyzna'), (3, 'Inne')])),
                ('wiek', models.IntegerField()),
                ('data_urodzenia', models.DateField()),
                ('data_dodania', models.DateTimeField(auto_now_add=True)),
                ('stanowisko', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='aplikacja.stanowisko')),
            ],
        ),
    ]
